/**
 * Action creators for the global store, declared in the shared layer so that
 * widgets/features/pages can dispatch them without importing slice modules
 * from `app/` (FSD-compliant).
 *
 * The action `type` strings match those auto-generated by Redux Toolkit's
 * `createSlice` (`<sliceName>/<reducerName>`) so dispatching one of these has
 * the exact same effect as importing the slice action directly.
 */
import type { UnknownAction } from '@reduxjs/toolkit';

import type { User } from '../types';

interface SetCredentialsPayload {
  user: User;
  accessToken: string;
  refreshToken: string;
}

interface UpdateTokensPayload {
  accessToken: string;
  refreshToken: string;
}

interface SetLanguageVoicePayload {
  lang: string;
  voiceURI: string;
}

export const setCredentials = (
  payload: SetCredentialsPayload,
): UnknownAction => ({ type: 'auth/setCredentials', payload });

export const updateTokens = (payload: UpdateTokensPayload): UnknownAction => ({
  type: 'auth/updateTokens',
  payload,
});

export const updateUser = (payload: Partial<User>): UnknownAction => ({
  type: 'auth/updateUser',
  payload,
});

export const logout = (): UnknownAction => ({ type: 'auth/logout' });

export const setLanguageVoice = (
  payload: SetLanguageVoicePayload,
): UnknownAction => ({ type: 'settings/setLanguageVoice', payload });

export const setNormalRate = (payload: number): UnknownAction => ({
  type: 'settings/setNormalRate',
  payload,
});

export const setSlowRate = (payload: number): UnknownAction => ({
  type: 'settings/setSlowRate',
  payload,
});

export const resetSpeech = (): UnknownAction => ({
  type: 'settings/resetSpeech',
});
